services:
  ekoru-gateway:
    image: ekoru-gateway:prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ekoru-gateway
    env_file:
      - .env.prod
    ports:
      - '9100:9000'
    networks:
      - ekoru-network
    volumes:
      - /home/ekoru/images:/app/images

networks:
  ekoru-network:
    external: true
