version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - addgroup
  - adduser
  - appgroup
  - appuser
  - dockerfile
  - ekoru
  - grafana
  - hashedpassword
  - helm
  - kubernetes
  - nestjs
  - noextension
  - originalname
  - postgres
  - postgresql
  - prisma
  - redis
  - supergraph
  - typeorm
  - wrongpassword
  - XVCJ
ignoreWords: []
import: []
