services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: gateway
    ports:
      - "4000:4000"
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
